# Generated by Django 5.1.6 on 2025-04-22 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "region_type",
                    models.CharField(
                        choices=[
                            ("Town", "Town"),
                            ("Forest Land", "Forest Land"),
                            ("Way", "Way"),
                            ("Healthy Forest", "Healthy Forest"),
                            ("Homes", "Homes"),
                        ],
                        max_length=50,
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("Forest Land", "Forest Land"),
                            ("Way", "Way"),
                            ("Healthy Forest", "Healthy Forest"),
                            ("Houses", "Houses"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.town"
                    ),
                ),
            ],
        ),
    ]
