# Generated by Django 5.1.6 on 2025-04-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_region_town_landtype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="region",
            name="added_on",
        ),
        migrations.AlterField(
            model_name="landtype",
            name="land_type",
            field=models.CharField(
                choices=[
                    ("Forest Land", "Forest Land"),
                    ("Way", "Way"),
                    ("Healthy Forest", "Healthy Forest"),
                    ("Homes", "Homes"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="town",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
