# Generated by Django 5.1.6 on 2025-05-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_result_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageanalysis",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="region_images/"),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="is_deforested",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="result",
            name="image",
            field=models.ImageField(upload_to="result_images/"),
        ),
    ]
